### ISSUE TITLE
Implementar responsividade

### ISSUE THREAD

**Issue by flauberjp** [GrudePB/GRUDEPB_FEST_2019#8]
O site tem de estar OK para ser visualizado em tamanhos diferentes de tela, por exemplo na tela de um celular.

**Comment by jhonattasantos** [comment]
O site não está responsivo?

**Comment by flauberjp** [comment]
Fechando a issue. Do meu lado a reponsividade estava quebrada pois minha tela estava com texto em 125%. Tudo bem que é um cenário válido ainda, mas de baixissima responsividade, já que colocando texto pro normal, 100%, o problema não aconteceu do meu lado.
